version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  backend:
    image: agnes4im/mern-backend:v1.0
    ports:
      - 9000:9000
    environment:
      DB_URL: mongodb://root:example@mongo:27017/
  frontend:
    image: agnes4im/mern-frontend:v1.0
    ports:
      - 3000:3000
volumes:
  mongo-data:
    driver: local